export type Language = 'en' | 'ru'

export const content = {
  en: {
    brand: {
      logoAlt: "Manuylov Studio",
      role: "Fullstack Developer",
    },
    nav: {
      aria: "Primary navigation",
      links: [
        { label: "Home", href: "/" },
        { label: "Projects", href: "/projects" },
        { label: "Services", href: "/services" },
        { label: "About", href: "/about" },
      ],
      languageLabel: "Switch language",
    },
    hero: {
      eyebrow: "Fullstack development for real business tasks",
      title: "Web products that look sharp and work end to end.",
      lead: "I design and build websites, web applications, and admin systems — from responsive interfaces to APIs, databases, and production-ready architecture.",
      primaryAction: "Discuss a project",
      secondaryAction: "Explore projects",
      highlightsLabel: "Why work with me",
      highlights: [
        { value: "Full cycle", label: "Interface, backend, and launch" },
        { value: "Work in stages", label: "You see progress throughout the project" },
        { value: "Built to grow", label: "Easy to maintain and extend" },
      ],
      visual: {
        ariaLabel: "A responsive commerce dashboard connected to an API and database",
        workspace: "Product workspace",
        dashboardKicker: "Overview",
        dashboardTitle: "Commerce dashboard",
        status: "Live",
        metricLabel: "Conversion",
        metricValue: "+24%",
        ordersLabel: "Orders",
        ordersValue: "1,284",
        mobileLabel: "Mobile experience",
        mobileValue: "Responsive",
        apiLabel: "API & database",
        apiValue: "Connected",
      },
    },
    overview: {
      kicker: "What I do",
      title: "From visual idea to working fullstack product.",
      services: [
        "Landing pages and portfolio websites",
        "Fullstack web apps with API and database",
        "Admin panels, dashboards, and internal tools",
        "Adaptive interfaces for desktop and mobile",
        "Backend services, integrations, and automation",
        "Polished UI with clear structure and motion",
      ],
    },
    servicesPage: {
      kicker: "Services",
      title: "From first screen to backend logic — one connected product.",
      lead: "I help turn a business task into a clear, responsive, and maintainable web product. The scope can start with one interface or cover the complete fullstack build.",
      includesLabel: "What is included",
      fitLabel: "Best for",
      items: [
        {
          id: "website",
          title: "Websites & product pages",
          description: "Fast multi-page websites, portfolios, landing pages, and service platforms with strong structure and a clear path to enquiry.",
          fit: "Businesses, experts, services, and product launches",
          includes: ["Information architecture", "Responsive UI", "Forms and integrations", "SEO-ready markup"],
        },
        {
          id: "app",
          title: "Fullstack web applications",
          description: "Complete products with interface, authentication, business logic, API, database models, and a structure ready for future development.",
          fit: "MVPs, customer portals, SaaS ideas, and internal products",
          includes: ["React application", "Backend API", "Authentication", "Database integration"],
        },
        {
          id: "dashboard",
          title: "Admin panels & dashboards",
          description: "Practical management interfaces with tables, filters, forms, roles, analytics, and workflows built around daily operations.",
          fit: "Operations, sales, content, analytics, and support teams",
          includes: ["Data-heavy UI", "Roles and permissions", "Charts and metrics", "Complex forms"],
        },
        {
          id: "backend",
          title: "Backend, API & integrations",
          description: "Reliable server-side foundations for existing or new interfaces: API design, validation, data access, and external service connections.",
          fit: "Products that need stable logic, data, or automation",
          includes: ["REST API", "Data validation", "Database access", "Third-party integrations"],
        },
      ],
    },
    aboutPage: {
      kicker: "About",
      title: "I connect product thinking with fullstack execution.",
      lead: "I am Alexandr Manuylov, a fullstack developer focused on websites, web applications, admin systems, and the infrastructure behind them.",
      bio: "My role is not limited to assembling screens. I clarify the user flow, shape the interface, design the data and API boundaries, and keep the codebase understandable as the product grows. I value calm communication, realistic scope, and details that make software feel finished.",
      principlesKicker: "Working principles",
      principlesTitle: "A practical approach to building digital products.",
      principles: [
        { number: "01", title: "Clarity before complexity", text: "Start with the real task, user flow, and smallest useful version before adding features." },
        { number: "02", title: "One connected system", text: "Treat UI, backend, data, and deployment as parts of the same product rather than isolated layers." },
        { number: "03", title: "Structure that can grow", text: "Use readable components, predictable APIs, and project boundaries that remain maintainable." },
        { number: "04", title: "Polish where it matters", text: "Pay attention to responsive behavior, states, accessibility, performance, and everyday usability." },
      ],
      collaborationKicker: "Collaboration",
      collaborationTitle: "A straightforward workflow with visible progress.",
      collaborationText: "I can join at the idea stage, continue an existing product, or take responsibility for a focused frontend, backend, or fullstack scope.",
      collaborationItems: ["Clear scope and priorities", "Regular progress updates", "Readable handoff and documentation", "Code prepared for further development"],
      availabilityLabel: "Current focus",
      availabilityValue: "Open to selected web projects",
    },
    stack: {
      kicker: "Stack",
      title: "Tools I use to design, build, and ship.",
      groups: [
        {
          id: "frontend",
          title: "Frontend",
          items: ["React", "TypeScript", "Vite", "Responsive UI", "Animation"],
        },
        {
          id: "backend",
          title: "Backend",
          items: [
            "Node.js",
            "Express",
            "REST API",
            "Auth flows",
            "Integrations",
          ],
        },
        {
          id: "data",
          title: "Data",
          items: [
            "PostgreSQL",
            "MongoDB",
            "Prisma",
            "Schema design",
            "Queries",
          ],
        },
        {
          id: "workflow",
          title: "Workflow",
          items: ["Git", "Deploy", "Clean code", "Testing mindset", "Docs"],
        },
      ],
    },
    process: {
      kicker: "Process",
      title: "How I move from idea to a usable release.",
      aria: "Process",
      steps: [
        {
          id: "understand",
          title: "Understand",
          text: "Clarify the goal, users, screens, data, and the smallest useful version of the product.",
        },
        {
          id: "build",
          title: "Build",
          text: "Create a stable frontend and backend structure with readable components, routes, and state.",
        },
        {
          id: "polish",
          title: "Polish",
          text: "Improve responsiveness, loading states, edge cases, accessibility, and visual rhythm.",
        },
        {
          id: "ship",
          title: "Ship",
          text: "Prepare the project for deploy, document the basics, and keep the code ready for growth.",
        },
      ],
    },
    projects: {
      kicker: "Selected work",
      title: "Selected products, built from interface to infrastructure.",
      action: "View all projects",
      challengeLabel: "Challenge",
      page: {
        kicker: "Project archive",
        title: "Fullstack work, documented as product case studies.",
        lead: "A growing collection of websites and fullstack products — from public interfaces to APIs, databases, and role-based admin systems.",
        roleLabel: "Role",
        yearLabel: "Year",
        statusLabel: "Status",
        featuresLabel: "Key features",
        demoAction: "Live demo",
        repositoryAction: "Repository",
        detailsAction: "View case study",
        backAction: "All projects",
        galleryLabel: "Product screens",
        openImageLabel: "Open image",
        previousImageLabel: "Previous image",
        nextImageLabel: "Next image",
        closeImageLabel: "Close image",
      },
      more: {
        kicker: "More work",
        title: "And many other digital products.",
        lead: "A selection of frontend concepts and business interfaces across logistics, hospitality, healthcare, construction, automotive, and commerce.",
        stackLabel: "React · TypeScript · Responsive UI · SEO",
        items: [
          { title: "Fuel Trans", category: "Logistics", image: "/projects/design-projects/fuel-trans.jpg" },
          { title: "Nova Trans", category: "Logistics", image: "/projects/design-projects/nova-trans.jpg" },
          { title: "Mare", category: "Restaurant", image: "/projects/design-projects/mare.jpg" },
          { title: "TeamHub", category: "Dashboard", image: "/projects/design-projects/teamhub.jpg" },
          { title: "Dentalis", category: "Healthcare", image: "/projects/design-projects/dentalis.jpg" },
          { title: "Drive & Go", category: "Car rental", image: "/projects/design-projects/drive-and-go.jpg" },
          { title: "Мясо & Огонь", category: "Restaurant", image: "/projects/design-projects/meat-and-fire.jpg" },
          { title: "СтройПроект", category: "Construction", image: "/projects/design-projects/stroyproject.jpg" },
          { title: "TechNova", category: "E-commerce", image: "/projects/design-projects/technova.jpg" },
        ],
      },
      items: [
        {
          slug: "gentlemans-room",
          title: "Gentleman's Room",
          type: "Fullstack booking platform",
          visual: "dashboard",
          status: "Live product",
          cover: "/projects/barbershop/cover.jpg",
          gallery: [
            "/projects/barbershop/booking.jpg",
            "/projects/barbershop/admin-dashboard.jpg",
            "/projects/barbershop/master-dashboard.jpg",
          ],
          challenge: "Create more than a presentation website: give clients a direct booking flow and the barbershop its own operational system without relying on third-party booking services.",
          solution: "A fullstack platform with public pages, booking without registration, automatic free-slot calculation, separate admin and barber accounts, schedule management, and Telegram alerts for new appointments.",
          stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Prisma"],
          role: "Fullstack development",
          year: "2026",
          features: ["Online booking and slot calculation", "Admin and barber roles", "Schedules and closed periods", "Telegram booking alerts"],
          demoHref: "",
          repositoryHref: "",
        },
        {
          slug: "projectflow",
          title: "ProjectFlow",
          type: "Fullstack project management app",
          visual: "dashboard",
          status: "Live demo",
          cover: "/projects/construction-app/projects.jpg",
          gallery: [
            "/projects/construction-app/login.jpg",
            "/projects/construction-app/team-tasks.jpg",
            "/projects/construction-app/users.jpg",
            "/projects/construction-app/activity.jpg",
            "/projects/construction-app/team-documents.jpg",
            "/projects/construction-app/project-stages.jpg",
          ],
          challenge: "Bring projects, teams, stages, tasks, documents, and progress tracking into one role-aware workspace instead of scattered operational tools.",
          solution: "A responsive fullstack dashboard with JWT authentication, PostgreSQL persistence, scoped permissions, task workflows, document storage, and a complete activity history.",
          stack: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL", "Prisma"],
          role: "Fullstack development",
          year: "2026",
          features: ["Admin, manager, and worker roles", "Projects, stages, and assigned tasks", "Status, priority, assignee, and date filters", "Project, stage, and task documents", "Activity history", "English and Russian interface"],
          demoHref: "https://construction-app-mauve.vercel.app",
          repositoryHref: "https://github.com/Aleks-man/construction-app",
        },
        {
          slug: "1c-crimea",
          title: "1C Crimea",
          type: "Frontend business website",
          visual: "website",
          status: "Frontend MVP",
          cover: "/projects/1s-project/cover.jpg",
          gallery: [
            "/projects/1s-project/catalog.jpg",
            "/projects/1s-project/industries.jpg",
            "/projects/1s-project/catalog-page.jpg",
            "/projects/1s-project/services.jpg",
          ],
          challenge: "Present 1C software sales, implementation, setup, and support as a clear regional service and help businesses quickly choose a suitable configuration.",
          solution: "A responsive multi-page frontend with a structured product catalog, industry scenarios, service pages, conversion-focused contact paths, and an API-ready architecture for future backend development.",
          stack: ["React", "TypeScript", "Vite", "React Router", "Responsive UI", "SEO"],
          role: "Frontend development",
          year: "2026",
          features: ["Filterable 1C product catalog", "Industry-specific solution navigation", "Service and support presentation", "Conversion-focused calls to action", "Semantic markup and SEO metadata", "Architecture prepared for API integration"],
          demoHref: "",
          repositoryHref: "",
        },
        {
          slug: "transgaz",
          title: "TransGaz Service",
          type: "Frontend service website",
          visual: "website",
          status: "Production business website",
          cover: "/projects/ugtransgas/cover.jpg",
          gallery: [
            "/projects/ugtransgas/services.jpg",
            "/projects/ugtransgas/works.jpg",
            "/projects/ugtransgas/pricing.jpg",
            "/projects/ugtransgas/request-form.jpg",
            "/projects/ugtransgas/vehicle-gallery.jpg",
            "/projects/ugtransgas/contacts.jpg",
            "/projects/ugtransgas/cta-footer.jpg",
          ],
          challenge: "Turn an established LPG installation service with real expertise, completed work, reviews, and regional demand into a convincing digital sales channel.",
          solution: "A conversion-focused multi-page frontend that explains the service, presents equipment packages and real installations, builds trust through business facts and reviews, and guides visitors to a calculation or inspection request.",
          stack: ["React", "TypeScript", "Vite", "React Router", "Responsive UI", "SEO"],
          role: "Frontend development",
          year: "2026",
          features: ["Service and equipment presentation", "Real installation portfolio by vehicle brand", "Package and pricing comparison", "Inspection and calculation request forms", "Business contacts and trust signals", "Semantic SEO structure and API-ready forms"],
          demoHref: "",
          repositoryHref: "",
        },
      ],
    },
    contact: {
      kicker: "Contact",
      title: "Ready to build something clean and useful?",
      text: "I am open to frontend, backend, and fullstack web projects.",
      email: "Email",
      emailAddress: "manuylovaleks@icloud.com",
      emailHref: "mailto:manuylovaleks@icloud.com",
      phone: "+7 (978) 609-20-60",
      phoneHref: "tel:+79786092060",
      phonesLabel: "Phones",
      telegram: "Telegram",
      telegramHref: "https://t.me/Aleks_Manuilov",
      whatsappHref: "https://wa.me/79780110617",
      viberHref: "viber://chat?number=%2B79780110617",
      messengerPhone: "+7 (978) 011-06-17",
      messengerPhoneHref: "tel:+79780110617",
      messengersLabel: "Messengers",
    },
    footer: {
      title: "Fullstack Developer Alex_Manuylov",
      top: "Back to top",
    },
  },
  ru: {
    brand: {
      logoAlt: "Manuylov Studio",
      role: "Fullstack разработчик",
    },
    nav: {
      aria: "Основная навигация",
      links: [
        { label: "Главная", href: "/" },
        { label: "Проекты", href: "/projects" },
        { label: "Услуги", href: "/services" },
        { label: "Обо мне", href: "/about" },
      ],
      languageLabel: "Переключить язык",
    },
    hero: {
      eyebrow: "Fullstack-разработка для реальных задач бизнеса",
      title: "Веб-продукты, которые хорошо выглядят и стабильно работают.",
      lead: "Проектирую и разрабатываю сайты, веб-приложения и админ-системы: от адаптивного интерфейса до API, базы данных и готовой к развитию архитектуры.",
      primaryAction: "Обсудить проект",
      secondaryAction: "Смотреть проекты",
      highlightsLabel: "Преимущества работы",
      highlights: [
        { value: "Полный цикл", label: "Интерфейс, backend и запуск" },
        { value: "Работа по этапам", label: "Вы видите результат по ходу работы" },
        { value: "Основа для роста", label: "Продукт удобно поддерживать и развивать" },
      ],
      visual: {
        ariaLabel: "Адаптивная панель управления, подключённая к API и базе данных",
        workspace: "Рабочая область",
        dashboardKicker: "Обзор",
        dashboardTitle: "Панель управления",
        status: "Онлайн",
        metricLabel: "Конверсия",
        metricValue: "+24%",
        ordersLabel: "Заказы",
        ordersValue: "1 284",
        mobileLabel: "Мобильная версия",
        mobileValue: "Адаптивно",
        apiLabel: "API и база данных",
        apiValue: "Подключены",
      },
    },
    overview: {
      kicker: "Что я делаю",
      title: "Помогаю пройти путь от идеи до работающего fullstack-продукта.",
      services: [
        "Лендинги, сайты-визитки и портфолио",
        "Fullstack-приложения с API и базой данных",
        "Админки, дашборды и внутренние инструменты",
        "Адаптивные интерфейсы для компьютеров и смартфонов",
        "Backend-сервисы, интеграции и автоматизация процессов",
        "Аккуратный UI с понятной структурой и уместной анимацией",
      ],
    },
    servicesPage: {
      kicker: "Услуги",
      title: "От первого экрана до backend-логики — единый связный продукт.",
      lead: "Помогаю превратить задачу бизнеса в понятный, адаптивный и поддерживаемый веб-продукт. Работа может начаться с одного интерфейса или охватить полную fullstack-разработку.",
      includesLabel: "Что входит",
      fitLabel: "Подходит для",
      items: [
        {
          id: "website",
          title: "Сайты и продуктовые страницы",
          description: "Быстрые многостраничные сайты, портфолио, лендинги и сервисные платформы с понятной структурой и путём к обращению.",
          fit: "Бизнеса, экспертов, услуг и запуска новых продуктов",
          includes: ["Структура контента", "Адаптивный UI", "Формы и интеграции", "SEO-разметка"],
        },
        {
          id: "app",
          title: "Fullstack веб-приложения",
          description: "Полноценные продукты с интерфейсом, авторизацией, бизнес-логикой, API, моделями данных и структурой для дальнейшего развития.",
          fit: "MVP, личных кабинетов, SaaS-идей и внутренних продуктов",
          includes: ["React-приложение", "Backend API", "Авторизация", "Интеграция базы данных"],
        },
        {
          id: "dashboard",
          title: "Админ-панели и dashboard",
          description: "Рабочие интерфейсы управления с таблицами, фильтрами, формами, ролями, аналитикой и повседневными сценариями.",
          fit: "Операционных, контентных, sales и support-команд",
          includes: ["Интерфейсы с данными", "Роли и доступы", "Графики и метрики", "Сложные формы"],
        },
        {
          id: "backend",
          title: "Backend, API и интеграции",
          description: "Надёжная серверная основа для нового или существующего интерфейса: проектирование API, валидация, данные и внешние сервисы.",
          fit: "Продуктов, которым нужна стабильная логика, данные или автоматизация",
          includes: ["REST API", "Валидация данных", "Работа с базой", "Внешние интеграции"],
        },
      ],
    },
    aboutPage: {
      kicker: "Обо мне",
      title: "Соединяю продуктовое мышление и fullstack-разработку.",
      lead: "Я Александр Мануйлов, fullstack-разработчик сайтов, веб-приложений, админ-систем и связанной с ними инфраструктуры.",
      bio: "Моя работа не ограничивается сборкой экранов. Я уточняю пользовательский сценарий, проектирую интерфейс, определяю границы данных и API и сохраняю кодовую базу понятной по мере развития продукта. Ценю спокойную коммуникацию, реалистичный объём работ и детали, благодаря которым продукт ощущается завершённым.",
      principlesKicker: "Принципы работы",
      principlesTitle: "Практичный подход к созданию цифровых продуктов.",
      principles: [
        { number: "01", title: "Ясность до сложности", text: "Сначала определяю реальную задачу, пользовательский путь и минимальную полезную версию продукта." },
        { number: "02", title: "Единая система", text: "Рассматриваю интерфейс, backend, данные и deployment как части одного продукта, а не отдельные слои." },
        { number: "03", title: "Структура для развития", text: "Использую читаемые компоненты, предсказуемые API и границы, которые удобно поддерживать." },
        { number: "04", title: "Внимание к важным деталям", text: "Прорабатываю responsive, состояния, доступность, производительность и повседневное удобство." },
      ],
      collaborationKicker: "Сотрудничество",
      collaborationTitle: "Понятный рабочий процесс и видимый прогресс.",
      collaborationText: "Могу подключиться на этапе идеи, продолжить существующий продукт или взять отдельную frontend, backend либо fullstack-задачу.",
      collaborationItems: ["Понятный объём и приоритеты", "Регулярные обновления прогресса", "Документация и передача проекта", "Код, готовый к дальнейшему развитию"],
      availabilityLabel: "Текущий фокус",
      availabilityValue: "Открыт к интересным веб-проектам",
    },
    stack: {
      kicker: "Стек",
      title:
        "Инструменты, с которыми я проектирую, разрабатываю и запускаю веб-проекты.",
      groups: [
        {
          id: "frontend",
          title: "Frontend",
          items: ["React", "TypeScript", "Vite", "Responsive UI", "Animation"],
        },
        {
          id: "backend",
          title: "Backend",
          items: [
            "Node.js",
            "Express",
            "REST API",
            "Auth flows",
            "Integrations",
          ],
        },
        {
          id: "data",
          title: "Data",
          items: [
            "PostgreSQL",
            "MongoDB",
            "Prisma",
            "Schema design",
            "Queries",
          ],
        },
        {
          id: "workflow",
          title: "Workflow",
          items: ["Git", "Deploy", "Clean code", "Testing mindset", "Docs"],
        },
      ],
    },
    process: {
      kicker: "Процесс",
      title: "Как я веду проект от идеи до готовой версии.",
      aria: "Процесс",
      steps: [
        {
          id: "understand",
          title: "Разобраться",
          text: "Уточняю цель проекта, аудиторию, ключевые экраны, данные и минимальную версию, которая уже приносит пользу.",
        },
        {
          id: "build",
          title: "Разработать",
          text: "Собираю frontend и backend на понятной основе: компоненты, роуты, состояние, API и работа с данными.",
        },
        {
          id: "polish",
          title: "Доработать",
          text: "Улучшаю адаптивность, состояния загрузки, крайние сценарии, доступность и общий визуальный ритм.",
        },
        {
          id: "ship",
          title: "Запустить",
          text: "Готовлю проект к деплою, описываю базовые детали и оставляю код в состоянии, с которым удобно двигаться дальше.",
        },
      ],
    },
    projects: {
      kicker: "Избранные проекты",
      title: "Избранные продукты — от интерфейса до инфраструктуры.",
      action: "Все проекты",
      challengeLabel: "Задача",
      page: {
        kicker: "Архив проектов",
        title: "Fullstack-проекты, оформленные как продуктовые кейсы.",
        lead: "Пополняемая коллекция сайтов и fullstack-продуктов: от публичных интерфейсов до API, баз данных и административных систем с ролевым доступом.",
        roleLabel: "Роль",
        yearLabel: "Год",
        statusLabel: "Статус",
        featuresLabel: "Ключевые функции",
        demoAction: "Демо",
        repositoryAction: "Репозиторий",
        detailsAction: "Смотреть проект",
        backAction: "Все проекты",
        galleryLabel: "Экраны продукта",
        openImageLabel: "Открыть изображение",
        previousImageLabel: "Предыдущее изображение",
        nextImageLabel: "Следующее изображение",
        closeImageLabel: "Закрыть изображение",
      },
      more: {
        kicker: "Другие работы",
        title: "И многие другие цифровые проекты.",
        lead: "Подборка frontend-концептов и бизнес-интерфейсов для логистики, ресторанов, медицины, строительства, автосервисов и электронной коммерции.",
        stackLabel: "React · TypeScript · Responsive UI · SEO",
        items: [
          { title: "Fuel Trans", category: "Логистика", image: "/projects/design-projects/fuel-trans.jpg" },
          { title: "Nova Trans", category: "Логистика", image: "/projects/design-projects/nova-trans.jpg" },
          { title: "Mare", category: "Ресторан", image: "/projects/design-projects/mare.jpg" },
          { title: "TeamHub", category: "Dashboard", image: "/projects/design-projects/teamhub.jpg" },
          { title: "Dentalis", category: "Медицина", image: "/projects/design-projects/dentalis.jpg" },
          { title: "Drive & Go", category: "Аренда автомобилей", image: "/projects/design-projects/drive-and-go.jpg" },
          { title: "Мясо & Огонь", category: "Ресторан", image: "/projects/design-projects/meat-and-fire.jpg" },
          { title: "СтройПроект", category: "Строительство", image: "/projects/design-projects/stroyproject.jpg" },
          { title: "TechNova", category: "E-commerce", image: "/projects/design-projects/technova.jpg" },
        ],
      },
      items: [
        {
          slug: "gentlemans-room",
          title: "Gentleman's Room",
          type: "Fullstack-сервис онлайн-записи",
          visual: "dashboard",
          status: "Рабочий продукт",
          cover: "/projects/barbershop/cover.jpg",
          gallery: [
            "/projects/barbershop/booking.jpg",
            "/projects/barbershop/admin-dashboard.jpg",
            "/projects/barbershop/master-dashboard.jpg",
          ],
          challenge: "Создать не просто презентационный сайт, а собственную систему барбершопа: дать клиентам прямую онлайн-запись и отказаться от зависимости от сторонних сервисов бронирования.",
          solution: "Fullstack-платформа с публичными страницами, записью без регистрации, автоматическим расчётом свободных слотов, отдельными кабинетами администратора и мастера, управлением расписанием и Telegram-уведомлениями о новых записях.",
          stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Prisma"],
          role: "Fullstack-разработка",
          year: "2026",
          features: ["Онлайн-запись и расчёт слотов", "Роли администратора и мастера", "Расписание и закрытые периоды", "Telegram-уведомления о записи"],
          demoHref: "",
          repositoryHref: "",
        },
        {
          slug: "projectflow",
          title: "ProjectFlow",
          type: "Fullstack-система управления проектами",
          visual: "dashboard",
          status: "Доступно демо",
          cover: "/projects/construction-app/projects.jpg",
          gallery: [
            "/projects/construction-app/login.jpg",
            "/projects/construction-app/team-tasks.jpg",
            "/projects/construction-app/users.jpg",
            "/projects/construction-app/activity.jpg",
            "/projects/construction-app/team-documents.jpg",
            "/projects/construction-app/project-stages.jpg",
          ],
          challenge: "Объединить проекты, команды, этапы, задачи, документы и контроль прогресса в одном рабочем пространстве с разграничением доступа.",
          solution: "Адаптивная fullstack-система с JWT-авторизацией, PostgreSQL, ролевыми разрешениями, рабочими сценариями задач, хранением документов и полной историей действий.",
          stack: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL", "Prisma"],
          role: "Fullstack-разработка",
          year: "2026",
          features: ["Роли администратора, менеджера и исполнителя", "Проекты, этапы и назначенные задачи", "Фильтры по статусу, приоритету, исполнителю и срокам", "Документы проекта, этапов и задач", "История действий", "Русский и английский интерфейс"],
          demoHref: "https://construction-app-mauve.vercel.app",
          repositoryHref: "https://github.com/Aleks-man/construction-app",
        },
        {
          slug: "1c-crimea",
          title: "1С в Крыму",
          type: "Frontend-сайт для бизнеса",
          visual: "website",
          status: "Frontend MVP",
          cover: "/projects/1s-project/cover.jpg",
          gallery: [
            "/projects/1s-project/catalog.jpg",
            "/projects/1s-project/industries.jpg",
            "/projects/1s-project/catalog-page.jpg",
            "/projects/1s-project/services.jpg",
          ],
          challenge: "Понятно представить продажу, внедрение, настройку и сопровождение 1С как региональную услугу и помочь бизнесу быстро подобрать подходящую конфигурацию.",
          solution: "Адаптивный многостраничный frontend с каталогом продуктов, отраслевыми сценариями, страницами услуг, понятными путями обращения и архитектурой, готовой к подключению будущего backend API.",
          stack: ["React", "TypeScript", "Vite", "React Router", "Responsive UI", "SEO"],
          role: "Frontend-разработка",
          year: "2026",
          features: ["Каталог продуктов 1С с фильтрацией", "Навигация по отраслевым решениям", "Презентация внедрения и сопровождения", "Конверсионные призывы к действию", "Семантическая разметка и SEO-метаданные", "Архитектура под подключение API"],
          demoHref: "",
          repositoryHref: "",
        },
        {
          slug: "transgaz",
          title: "СТО ТрансГаз",
          type: "Frontend-сайт сервисного бизнеса",
          visual: "website",
          status: "Рабочий сайт бизнеса",
          cover: "/projects/ugtransgas/cover.jpg",
          gallery: [
            "/projects/ugtransgas/services.jpg",
            "/projects/ugtransgas/works.jpg",
            "/projects/ugtransgas/pricing.jpg",
            "/projects/ugtransgas/request-form.jpg",
            "/projects/ugtransgas/vehicle-gallery.jpg",
            "/projects/ugtransgas/contacts.jpg",
            "/projects/ugtransgas/cta-footer.jpg",
          ],
          challenge: "Превратить работающий сервис по установке ГБО с реальным опытом, выполненными работами, отзывами и региональным спросом в убедительный цифровой канал продаж.",
          solution: "Конверсионный многостраничный frontend, который объясняет услугу, показывает комплекты оборудования и реальные установки, усиливает доверие фактами о бизнесе и отзывами и ведёт посетителя к расчёту или записи на осмотр.",
          stack: ["React", "TypeScript", "Vite", "React Router", "Responsive UI", "SEO"],
          role: "Frontend-разработка",
          year: "2026",
          features: ["Презентация услуг и оборудования", "Галерея реальных установок по маркам автомобилей", "Сравнение комплектов и стоимости", "Формы записи на осмотр и запроса расчёта", "Контакты бизнеса и элементы доверия", "Семантическая SEO-структура и формы, готовые к API"],
          demoHref: "",
          repositoryHref: "",
        },
      ],
    },
    contact: {
      kicker: "Контакты",
      title: "Нужен сайт, backend или полноценное веб-приложение?",
      text: "Открыт к frontend, backend и fullstack-проектам.",
      email: "Email",
      emailAddress: "manuylovaleks@icloud.com",
      emailHref: "mailto:manuylovaleks@icloud.com",
      phone: "+7 (978) 609-20-60",
      phoneHref: "tel:+79786092060",
      phonesLabel: "Телефоны",
      telegram: "Telegram",
      telegramHref: "https://t.me/Aleks_Manuilov",
      whatsappHref: "https://wa.me/79780110617",
      viberHref: "viber://chat?number=%2B79780110617",
      messengerPhone: "+7 (978) 011-06-17",
      messengerPhoneHref: "tel:+79780110617",
      messengersLabel: "Мессенджеры",
    },
    footer: {
      title: "Fullstack Developer Alex_Manuylov",
      top: "Наверх",
    },
  },
} as const;

export type PortfolioContent = (typeof content)[Language]
export type StackIconId = PortfolioContent['stack']['groups'][number]['id']
export type ProcessIconId = PortfolioContent['process']['steps'][number]['id']
export type ServiceIconId = PortfolioContent['servicesPage']['items'][number]['id']
