export const englishProjects = {
      kicker: "Selected work",
      title: "From business websites to complete web systems.",
      action: "View all projects",
      challengeLabel: "Challenge",
      page: {
        kicker: "Projects",
        title: "Websites and web applications I have developed.",
        lead: "Each project presents the original task, the solution I developed, key functionality, and the technologies used.",
        roleLabel: "Role",
        yearLabel: "Year",
        statusLabel: "Status",
        resultLabel: "Result",
        featuresLabel: "Key features",
        demoAction: "Open demo",
        demoAccessLabel: "Demo access",
        demoAdminAction: "Open admin panel",
        demoLoginLabel: "Login",
        demoPasswordLabel: "Password",
        detailsAction: "Project details",
        backAction: "All projects",
        projectNavigationLabel: "More projects",
        previousProjectLabel: "Previous project",
        nextProjectLabel: "Next project",
        galleryLabel: "Project screens",
        openImageLabel: "Open image",
        previousImageLabel: "Previous image",
        nextImageLabel: "Next image",
        closeImageLabel: "Close image",
      },
      more: {
        kicker: "More work",
        title: "Websites and interfaces for different business sectors.",
        lead: "A selection of frontend concepts and business interfaces across logistics, hospitality, healthcare, construction, automotive, and commerce.",
        stackLabel: "React · TypeScript · Responsive layout · SEO",
        items: [
          {
            title: "Fuel Trans",
            category: "Logistics",
            image: "/projects/design-projects/fuel-trans.jpg",
          },
          {
            title: "Nova Trans",
            category: "Logistics",
            image: "/projects/design-projects/nova-trans.jpg",
          },
          {
            title: "Mare",
            category: "Restaurant",
            image: "/projects/design-projects/mare.jpg",
          },
          {
            title: "TeamHub",
            category: "Admin panel",
            image: "/projects/design-projects/teamhub.jpg",
          },
          {
            title: "Dentalis",
            category: "Healthcare",
            image: "/projects/design-projects/dentalis.jpg",
          },
          {
            title: "Drive & Go",
            category: "Car rental",
            image: "/projects/design-projects/drive-and-go.jpg",
          },
          {
            title: "Мясо & Огонь",
            category: "Restaurant",
            image: "/projects/design-projects/meat-and-fire.jpg",
          },
          {
            title: "СтройПроект",
            category: "Construction",
            image: "/projects/design-projects/stroyproject.jpg",
          },
          {
            title: "TechNova",
            category: "Online store",
            image: "/projects/design-projects/technova.jpg",
          },
        ],
      },
      items: [
        {
          slug: "gentlemans-room",
          title: "Gentleman's Room",
          type: "Online booking service for a barbershop",
          visual: "dashboard",
          status: "Working MVP",
          cover: "/projects/barbershop/cover.jpg",
          gallery: [
            "/projects/barbershop/booking.jpg",
            "/projects/barbershop/admin-dashboard.jpg",
            "/projects/barbershop/master-dashboard.jpg",
          ],
          challenge:
            "Combine a presentation website, online booking, and schedule management in one product without relying on third-party booking services.",
          solution:
            "A fullstack system with public pages, booking without registration, automatic availability calculation, admin and barber accounts, schedule management, and Telegram notifications.",
          result:
            "A single service where clients choose a service, barber, and time, while the team manages schedules and appointments through its own system.",
          stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Prisma"],
          role: "Fullstack development",
          year: "2026",
          features: [
            "Online booking and availability calculation",
            "Admin and barber roles",
            "Schedule and closed-period management",
            "Telegram notifications for new bookings",
          ],
          demoHref: "https://barbershop-man.vercel.app/",
          demoAccess: {
            href: "https://barbershop-man.vercel.app/admin",
            login: "admin",
            password: "admin123",
          },
        },
        {
          slug: "projectflow",
          title: "ProjectFlow",
          type: "Project management system",
          visual: "dashboard",
          status: "Live demo",
          cover: "/projects/construction-app/projects.jpg",
          gallery: [
            "/projects/construction-app/login.jpg",
            "/projects/construction-app/team-tasks.jpg",
            "/projects/construction-app/users.jpg",
            "/projects/construction-app/activity.jpg",
            "/projects/construction-app/team-documents.jpg",
            "/projects/construction-app/project-stages.jpg",
          ],
          challenge:
            "Bring projects, teams, stages, tasks, documents, and progress tracking into one role-aware workspace instead of scattered operational tools.",
          solution:
            "A fullstack application with JWT-based authentication, role-based access, task management, document storage, and user activity history.",
          result:
            "All key processes are brought together in one system where participants can see current progress, assigned tasks, deadlines, and areas of responsibility.",
          stack: [
            "React",
            "TypeScript",
            "Node.js",
            "Express",
            "PostgreSQL",
            "Prisma",
          ],
          role: "Fullstack development",
          year: "2026",
          features: [
            "Admin, manager, and worker roles",
            "Projects, stages, and assigned tasks",
            "Status, priority, assignee, and date filters",
            "Project, stage, and task documents",
            "User activity history",
            "English and Russian interface",
          ],
          demoHref: "https://construction-app-mauve.vercel.app",
          demoAccess: {
            href: "https://construction-app-mauve.vercel.app",
            login: "admin@test.com",
            password: "DemoAdmin_2026_App_passW",
          },
        },
        {
          slug: "1c-crimea",
          title: "1C Crimea",
          type: "Business services website",
          visual: "website",
          status: "Completed frontend",
          cover: "/projects/1s-project/cover.jpg",
          gallery: [
            "/projects/1s-project/catalog.jpg",
            "/projects/1s-project/industries.jpg",
            "/projects/1s-project/catalog-page.jpg",
            "/projects/1s-project/services.jpg",
          ],
          challenge:
            "Clearly present 1C software sales, implementation, setup, and support, and help businesses quickly choose the right configuration.",
          solution:
            "A responsive multi-page website with a product catalog, industry solutions, service pages, and clear paths to making an enquiry.",
          result:
            "1C products and services are organised into a clear structure that helps visitors choose a solution and request a consultation.",
          stack: [
            "React",
            "TypeScript",
            "Vite",
            "React Router",
            "Responsive layout",
            "SEO",
          ],
          role: "Frontend development",
          year: "2026",
          features: [
            "Filterable 1C product catalog",
            "Industry-specific solution navigation",
            "Service and support presentation",
            "Clear paths to enquiry",
            "Semantic markup and SEO metadata",
            "Architecture prepared for API integration",
          ],
          demoHref: "https://1s-project-vet.vercel.app/",
          demoAccess: null,
        },
        {
          slug: "transgaz",
          title: "TransGaz Service",
          type: "Automotive service website",
          visual: "website",
          status: "Completed website",
          cover: "/projects/ugtransgas/cover.jpg",
          gallery: [
            "/projects/ugtransgas/services.jpg",
            "/projects/ugtransgas/works.jpg",
            "/projects/ugtransgas/pricing.jpg",
            "/projects/ugtransgas/request-form.jpg",
            "/projects/ugtransgas/vehicle-gallery.jpg",
            "/projects/ugtransgas/contacts.jpg",
            "/projects/ugtransgas/cta-footer.jpg",
          ],
          challenge:
            "Create a modern website that clearly presents LPG installation services, showcases real work, and helps generate inspection and price estimate requests.",
          solution:
            "A responsive multi-page website with service descriptions, equipment packages, an installation gallery, reviews, pricing, and enquiry forms.",
          result:
            "Services, equipment, completed work, and reviews are combined into a clear journey from discovering the company to booking an inspection or requesting an estimate.",
          stack: [
            "React",
            "TypeScript",
            "Vite",
            "React Router",
            "Responsive layout",
            "SEO",
          ],
          role: "Frontend development",
          year: "2026",
          features: [
            "Service and equipment presentation",
            "Installation gallery by vehicle brand",
            "Package and pricing comparison",
            "Inspection and calculation request forms",
            "Contact details and trust signals",
            "Semantic SEO structure",
          ],
          demoHref: "https://ugtransgas.vercel.app/",
          demoAccess: null,
        },
      ],
    } as const
