export const russianProjects = {
      kicker: "Избранные проекты",
      title: "От сайтов для бизнеса до полноценных веб-систем.",
      action: "Все проекты",
      challengeLabel: "Задача",

      page: {
        kicker: "Проекты",
        title: "Сайты и веб-приложения, которые я разработал.",
        lead: "В каждом проекте показываю поставленную задачу, разработанное решение, ключевые функции и использованные технологии.",
        roleLabel: "Роль",
        yearLabel: "Год",
        statusLabel: "Статус",
        resultLabel: "Результат",
        featuresLabel: "Ключевые функции",
        demoAction: "Открыть демо",
        demoAccessLabel: "Доступ к демо",
        demoAdminAction: "Открыть админ-панель",
        demoLoginLabel: "Логин",
        demoPasswordLabel: "Пароль",
        shareAction: "Поделиться проектом",
        shareCopied: "Ссылка скопирована",
        shareText: "Посмотрите проект",
        detailsAction: "Подробнее о проекте",
        backAction: "Все проекты",
        projectNavigationLabel: "Другие проекты",
        previousProjectLabel: "Предыдущий проект",
        nextProjectLabel: "Следующий проект",
        galleryLabel: "Экраны проекта",
        coverImageLabel: "Обложка проекта",
        openImageLabel: "Открыть изображение",
        previousImageLabel: "Предыдущее изображение",
        nextImageLabel: "Следующее изображение",
        closeImageLabel: "Закрыть изображение",
      },

      more: {
        kicker: "Другие работы",
        title: "Сайты и интерфейсы для разных направлений бизнеса.",
        lead: "Подборка сайтов и интерфейсных концепций для логистики, ресторанов, медицины, строительства, автосервисов и электронной коммерции.",
        stackLabel: "React · TypeScript · Адаптивная вёрстка · SEO",
        items: [
          {
            title: "Fuel Trans",
            category: "Логистика",
            image: "/projects/design-projects/fuel-trans.jpg",
          },
          {
            title: "Nova Trans",
            category: "Логистика",
            image: "/projects/design-projects/nova-trans.jpg",
          },
          {
            title: "Mare",
            category: "Ресторан",
            image: "/projects/design-projects/mare.jpg",
          },
          {
            title: "TeamHub",
            category: "Админ-панель",
            image: "/projects/design-projects/teamhub.jpg",
          },
          {
            title: "Dentalis",
            category: "Медицина",
            image: "/projects/design-projects/dentalis.jpg",
          },
          {
            title: "Drive & Go",
            category: "Аренда автомобилей",
            image: "/projects/design-projects/drive-and-go.jpg",
          },
          {
            title: "Мясо & Огонь",
            category: "Ресторан",
            image: "/projects/design-projects/meat-and-fire.jpg",
          },
          {
            title: "СтройПроект",
            category: "Строительство",
            image: "/projects/design-projects/stroyproject.jpg",
          },
          {
            title: "TechNova",
            category: "Интернет-магазин",
            image: "/projects/design-projects/technova.jpg",
          },
        ],
      },

      items: [
        {
          slug: "gentlemans-room",
          title: "Gentleman's Room",
          type: "Сервис онлайн-записи для барбершопа",
          visual: "dashboard",
          status: "Рабочий MVP",
          cover: "/projects/barbershop/cover.jpg",
          thumbnail: "/projects/barbershop/cover-mobile.jpg",
          gallery: [
            "/projects/barbershop/booking.jpg",
            "/projects/barbershop/admin-dashboard.jpg",
            "/projects/barbershop/master-dashboard.jpg",
          ],
          challenge:
            "Объединить презентационный сайт, онлайн-запись и управление расписанием в одном продукте без зависимости от сторонних сервисов бронирования.",
          solution:
            "Fullstack-система с публичными страницами, записью без регистрации, автоматическим расчётом свободного времени, кабинетами администратора и мастера, управлением расписанием и Telegram-уведомлениями.",
          result:
            "Создан единый сервис, в котором клиент выбирает услугу, мастера и время, а команда управляет расписанием и записями через собственную систему.",
          stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "Prisma"],
          role: "Fullstack-разработка",
          year: "2026",
          features: [
            "Онлайн-запись и расчёт свободного времени",
            "Роли администратора и мастера",
            "Управление расписанием и закрытыми периодами",
            "Telegram-уведомления о новых записях",
          ],
          demoHref: "https://barbershop-man.vercel.app/",
          demoAccess: {
            href: "https://barbershop-man.vercel.app/admin",
            login: "admin",
            password: "admin123",
          },
        },
        {
          slug: "projectflow",
          title: "ProjectFlow",
          type: "Система управления проектами",
          visual: "dashboard",
          status: "Доступно демо",
          cover: "/projects/construction-app/projects.jpg",
          thumbnail: "/projects/construction-app/projects-mobile.jpg",
          gallery: [
            "/projects/construction-app/login.jpg",
            "/projects/construction-app/team-tasks.jpg",
            "/projects/construction-app/users.jpg",
            "/projects/construction-app/activity.jpg",
            "/projects/construction-app/team-documents.jpg",
            "/projects/construction-app/project-stages.jpg",
          ],
          challenge:
            "Объединить проекты, команды, этапы, задачи, документы и контроль прогресса в одном рабочем пространстве с разграничением доступа.",
          solution:
            "Fullstack-приложение с аутентификацией на основе JWT, ролевым доступом, управлением задачами, хранением документов и историей действий пользователей.",
          result:
            "Все ключевые процессы собраны в одной системе, где участники видят текущий прогресс, назначенные задачи, сроки и зоны ответственности.",
          stack: [
            "React",
            "TypeScript",
            "Node.js",
            "Express",
            "PostgreSQL",
            "Prisma",
          ],
          role: "Fullstack-разработка",
          year: "2026",
          features: [
            "Роли администратора, менеджера и исполнителя",
            "Проекты, этапы и назначенные задачи",
            "Фильтры по статусу, приоритету, исполнителю и срокам",
            "Документы проектов, этапов и задач",
            "История действий пользователей",
            "Русский и английский интерфейс",
          ],
          demoHref: "https://construction-app-mauve.vercel.app",
          demoAccess: {
            href: "https://construction-app-mauve.vercel.app",
            login: "admin@test.com",
            password: "DemoAdmin_2026_App_passW",
          },
        },
        {
          slug: "1c-crimea",
          title: "1С в Крыму",
          type: "Сайт услуг для бизнеса",
          visual: "website",
          status: "Готовый frontend",
          cover: "/projects/1s-project/cover.jpg",
          thumbnail: "/projects/1s-project/cover-mobile.jpg",
          gallery: [
            "/projects/1s-project/catalog.jpg",
            "/projects/1s-project/industries.jpg",
            "/projects/1s-project/catalog-page.jpg",
            "/projects/1s-project/services.jpg",
          ],
          challenge:
            "Понятно представить продажу, внедрение, настройку и сопровождение 1С и помочь бизнесу быстро подобрать подходящую конфигурацию.",
          solution:
            "Адаптивный многостраничный сайт с каталогом продуктов, отраслевыми решениями, страницами услуг и понятными сценариями перехода к обращению.",
          result:
            "Продукты и услуги 1С собраны в понятную структуру, которая помогает посетителю выбрать решение и перейти к консультации.",
          stack: [
            "React",
            "TypeScript",
            "Vite",
            "React Router",
            "Адаптивная вёрстка",
            "SEO",
          ],
          role: "Frontend-разработка",
          year: "2026",
          features: [
            "Каталог продуктов 1С с фильтрацией",
            "Навигация по отраслевым решениям",
            "Презентация внедрения и сопровождения",
            "Сценарии перехода к обращению",
            "Семантическая разметка и SEO-метаданные",
            "Архитектура под подключение API",
          ],
          demoHref: "https://1s-project-vet.vercel.app/",
          demoAccess: null,
        },
        {
          slug: "transgaz",
          title: "СТО ТрансГаз",
          type: "Сайт автомобильного сервиса",
          visual: "website",
          status: "Готовый сайт",
          cover: "/projects/ugtransgas/cover.jpg",
          thumbnail: "/projects/ugtransgas/cover-mobile.jpg",
          gallery: [
            "/projects/ugtransgas/services.jpg",
            "/projects/ugtransgas/works.jpg",
            "/projects/ugtransgas/pricing.jpg",
            "/projects/ugtransgas/request-form.jpg",
            "/projects/ugtransgas/vehicle-gallery.jpg",
            "/projects/ugtransgas/contacts.jpg",
            "/projects/ugtransgas/cta-footer.jpg",
          ],
          challenge:
            "Создать современный сайт, который понятно представляет услуги по установке ГБО, показывает реальные работы и помогает получать заявки на осмотр и расчёт стоимости.",
          solution:
            "Адаптивный многостраничный сайт с описанием услуг, комплектами оборудования, галереей установок, отзывами, ценами и формами обращения.",
          result:
            "Услуги, оборудование, реальные работы и отзывы объединены в понятный путь от знакомства с компанией до записи на осмотр или запроса расчёта.",
          stack: [
            "React",
            "TypeScript",
            "Vite",
            "React Router",
            "Адаптивная вёрстка",
            "SEO",
          ],
          role: "Frontend-разработка",
          year: "2026",
          features: [
            "Презентация услуг и оборудования",
            "Галерея установок по маркам автомобилей",
            "Сравнение комплектов и стоимости",
            "Формы записи на осмотр и запроса расчёта",
            "Контакты и элементы доверия",
            "Семантическая SEO-структура",
          ],
          demoHref: "https://ugtransgas.vercel.app/",
          demoAccess: null,
        },
      ],
    } as const
